/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp2crypto;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author carlbelanger
 */
public class ClientServer extends javax.swing.JFrame {

    private final Generator generator = new Generator();
    private Server server = new Server();
    private Client client = new Client();
    private Status status = Status.ConnectionClosed;
    private boolean messageClientSended = false;
    private boolean messageServerSended = false;
    
    /**
     * Creates new form ClientServer
     */
    public ClientServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOperation = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNs = new javax.swing.JTextField();
        btnStep2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIV4 = new javax.swing.JTextField();
        btnStep4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIV6 = new javax.swing.JTextField();
        btnStep6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIV8 = new javax.swing.JTextField();
        btnStep8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIV10 = new javax.swing.JTextField();
        btnStep10 = new javax.swing.JButton();
        txtNs2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNs1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblServerMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMessageEchange = new javax.swing.JTextField();
        btnEnvoyer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIV9 = new javax.swing.JTextField();
        txtNc1 = new javax.swing.JTextField();
        txtIV7 = new javax.swing.JTextField();
        txtIV5 = new javax.swing.JTextField();
        txtK0 = new javax.swing.JTextField();
        txtNc = new javax.swing.JTextField();
        btnStep1 = new javax.swing.JButton();
        btnStep3 = new javax.swing.JButton();
        btnStep5 = new javax.swing.JButton();
        btnStep7 = new javax.swing.JButton();
        btnStep9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        radioTransfert = new javax.swing.JRadioButton();
        radioQuitter = new javax.swing.JRadioButton();
        txtDestination = new javax.swing.JTextField();
        txtMontant = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnRecommencer = new javax.swing.JButton();
        lblClientMessage = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Serveur");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel1.setOpaque(true);

        jLabel4.setText("Ns");

        txtNs.setName(""); // NOI18N
        txtNs.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep2.setText("2");
        btnStep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep2ActionPerformed(evt);
            }
        });

        jLabel5.setText("IV");

        txtIV4.setName(""); // NOI18N
        txtIV4.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep4.setText("4");
        btnStep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep4ActionPerformed(evt);
            }
        });

        jLabel6.setText("IV");

        txtIV6.setName(""); // NOI18N
        txtIV6.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep6.setText("6");
        btnStep6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep6ActionPerformed(evt);
            }
        });

        jLabel7.setText("IV");

        txtIV8.setName(""); // NOI18N
        txtIV8.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep8.setText("8");
        btnStep8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep8ActionPerformed(evt);
            }
        });

        jLabel8.setText("IV");

        txtIV10.setName(""); // NOI18N
        txtIV10.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep10.setText("10");
        btnStep10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep10ActionPerformed(evt);
            }
        });

        txtNs2.setName(""); // NOI18N
        txtNs2.setPreferredSize(new java.awt.Dimension(25, 28));

        jLabel9.setText("Ns2");

        txtNs1.setName(""); // NOI18N
        txtNs1.setPreferredSize(new java.awt.Dimension(25, 28));

        jLabel10.setText("Ns1");

        lblServerMessage.setText("Résultat de vérification (échec ou réussite): ");
        lblServerMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(414, 414, 414)
                                        .addComponent(btnStep6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(430, 430, 430)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(402, 402, 402)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNs1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(txtIV6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnStep8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnStep10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(32, 32, 32))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNs2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtIV8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)
                                                .addComponent(txtIV10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jLabel4))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(txtNs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(txtIV4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(99, 99, 99)
                                .addComponent(jLabel10)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblServerMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtNs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStep4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStep2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStep6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIV10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnStep8)
                                    .addComponent(btnStep10)))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblServerMessage)
                .addGap(52, 52, 52))
        );

        txtNs.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Réseau");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel2.setOpaque(true);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Message échangé");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMessageEchange, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtMessageEchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnvoyer))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Client");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setOpaque(true);

        jLabel11.setText("Nc");

        jLabel12.setText("K0");

        jLabel13.setText("IV");

        jLabel14.setText("IV");

        jLabel15.setText("IV");

        jLabel16.setText("Nc1");

        txtIV9.setName(""); // NOI18N
        txtIV9.setPreferredSize(new java.awt.Dimension(25, 28));
        txtIV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIV9ActionPerformed(evt);
            }
        });

        txtNc1.setName(""); // NOI18N
        txtNc1.setPreferredSize(new java.awt.Dimension(25, 28));

        txtIV7.setName(""); // NOI18N
        txtIV7.setPreferredSize(new java.awt.Dimension(25, 28));

        txtIV5.setName(""); // NOI18N
        txtIV5.setPreferredSize(new java.awt.Dimension(25, 28));

        txtK0.setName(""); // NOI18N
        txtK0.setPreferredSize(new java.awt.Dimension(25, 28));

        txtNc.setName(""); // NOI18N
        txtNc.setPreferredSize(new java.awt.Dimension(25, 28));

        btnStep1.setText("1");
        btnStep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep1ActionPerformed(evt);
            }
        });

        btnStep3.setText("3");
        btnStep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep3ActionPerformed(evt);
            }
        });

        btnStep5.setText("5");
        btnStep5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep5ActionPerformed(evt);
            }
        });

        btnStep7.setText("7");
        btnStep7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep7ActionPerformed(evt);
            }
        });

        btnStep9.setText("9");
        btnStep9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStep9ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel17.setText("Authentification");

        jLabel18.setBackground(new java.awt.Color(153, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Numéro ID");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(153, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mot de passe");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel19.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel17)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel20.setText("Opérations");

        btnGrpOperation.add(radioTransfert);
        radioTransfert.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioTransfert.setSelected(true);
        radioTransfert.setText("TRANSFERT");
        radioTransfert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTransfertActionPerformed(evt);
            }
        });

        btnGrpOperation.add(radioQuitter);
        radioQuitter.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioQuitter.setText("QUITTER");

        txtDestination.setToolTipText("");

        jLabel21.setText("Destination");

        jLabel22.setText("Montant");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioTransfert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioQuitter))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel21)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel22)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTransfert)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioQuitter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRecommencer.setText("Recommencer");
        btnRecommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecommencerActionPerformed(evt);
            }
        });

        lblClientMessage.setText("Résultat de vérification (échec ou réussite): ");
        lblClientMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtNc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(txtK0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStep5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel13))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(txtIV5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel14))
                                    .addComponent(btnStep7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtIV7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNc1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(115, 115, 115))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtIV9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnStep9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblClientMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRecommencer))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStep1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIV9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStep9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtK0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStep3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStep5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStep7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecommencer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addComponent(lblClientMessage)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep3ActionPerformed
        
        if (status == Status.WaitingForConnection && messageServerSended) {
            this.status = Status.ServerConnection;
        }
        if (!messageServerSended) {
            error("La réponse du serveur n'a pas été encore reçu.");
            return;
        }
        if (status != Status.ServerConnection) {
            error("Le client n'est pas prêt pour cette étape.");
            return;
        }
        client.setStatus(status);
        
        if (txtK0.getText().isEmpty()) {
            txtK0.setText(generator.genRandomK());
        }
        int k0 = getAsInt(txtK0.getText());
        if (k0 < 2 || k0 > 3810) {
            error("K0 doit être entre 2 et 3810");
            return;
        }
        client.inject(new FakeGenerator(txtK0.getText()));
        String message = client.sendBack();
        txtMessageEchange.setText(message);
        messageClientSended = false;
    }//GEN-LAST:event_btnStep3ActionPerformed

    private void radioTransfertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTransfertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTransfertActionPerformed

    private void btnStep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep1ActionPerformed
        
        if (status != Status.ConnectionClosed) {
            error("Le client n'est pas prêt pour cette étape.");
            return;
        }
        
        client.setStatus(status);
        
        if (txtNc.getText().isEmpty()) {
            txtNc.setText(generator.genRandomN());
        }
        int tmpNc = getAsInt(txtNc.getText());
        if (tmpNc < 0 || tmpNc > 99999) {
            error("Nc doit être entre 0 et 99999");
            return;
        }
        client.inject(new FakeGenerator(txtNc.getText()));
        String message = client.reveiveAndSendBack(null);
        txtMessageEchange.setText(message);
        messageClientSended = false;
    }//GEN-LAST:event_btnStep1ActionPerformed

    private void btnRecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecommencerActionPerformed
        //if ("0".equals(txtRecommencer.getText())) {
            client = new Client();
            server = new Server();
            status = Status.ConnectionClosed;
            String message = "Résultat de vérification (échec ou réussite): ";
            lblClientMessage.setText(message);
            lblServerMessage.setText(message);
        /*} else if ("1".equals(txtRecommencer.getText())) {
        }*/
    }//GEN-LAST:event_btnRecommencerActionPerformed

    private void btnStep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep4ActionPerformed
        
        if (status == Status.ServerConnection && messageClientSended) {
            this.status = Status.ClientConnected;
        }
        if (!messageClientSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.ClientConnected) {
            error("Le serveur n'est pas prêt pour cette étape.");
            return;
        }
        server.setStatus(status);
        
        if (txtIV4.getText().isEmpty()) {
            txtIV4.setText(generator.genRandomIV());
        }
        if (txtIV4.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV4.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        server.inject(new FakeGenerator(txtIV4.getText()));
        String message = server.sendBack();
        txtMessageEchange.setText(message);
        messageServerSended = false;
    }//GEN-LAST:event_btnStep4ActionPerformed

    private void txtIV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIV9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIV9ActionPerformed

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
        
        boolean isServer = false;
        switch (status) {
            case ConnectionClosed:
                server.setStatus(Status.WaitingForConnection);
                isServer = true;
                break;
            case ServerConnection:
                server.setStatus(Status.ClientConnected);
                isServer = true;
                break;
            case Negociating:
                server.setStatus(Status.TrustEstablished);
                isServer = true;
                break;
            case AtemptingLogging:
                server.setStatus(Status.Authenticate);
                isServer = true;
                break;
            case Logged:
                server.setStatus(Status.ClientLogged);
                isServer = true;
                break;
            case WaitingForConnection:
                client.setStatus(Status.ServerConnection);
                isServer = false;
                break;
            case ClientConnected:
                client.setStatus(Status.Negociating);
                isServer = false;
                break;
            case TrustEstablished: 
                client.setStatus(Status.AtemptingLogging);
                isServer = false;
                break;
            case Authenticate:
                client.setStatus(Status.Logged);
                isServer = false;
                break;
            case ClientLogged:
                client.setStatus(Status.ConnectionClosed);
                isServer = false;
                break;    
        }
        
        if (isServer) {
            boolean serverSuccess = server.reveive(txtMessageEchange.getText());
            String serverMessage = "Résultat de vérification (échec ou réussite): ";
            lblClientMessage.setText(serverMessage);
            serverMessage += serverSuccess ? "RÉUSSITE" : "ÉCHEC";
            lblServerMessage.setText(serverMessage);
            messageClientSended = serverSuccess;
        } else {
            boolean clientSucess = client.reveive(txtMessageEchange.getText());
            String clientMessage = "Résultat de vérification (échec ou réussite): ";
            lblServerMessage.setText(clientMessage);
            clientMessage += clientSucess ? "RÉUSSITE" : "ÉCHEC";
            lblClientMessage.setText(clientMessage);
            messageServerSended = clientSucess;
        }
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void btnStep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep2ActionPerformed
        
        if (status == Status.ConnectionClosed && messageClientSended) {
            this.status = Status.WaitingForConnection;
        }
        if (!messageClientSended) {
            error("No response sended from the client yet.");
            return;
        }
        if (status != Status.WaitingForConnection) {
            error("Server not ready for this step");
            return;
        }
        server.setStatus(status);
        
        if (txtNs.getText().isEmpty()) {
            txtNs.setText(generator.genRandomN());
        }
        int ns = getAsInt(txtNs.getText());
        if (ns < 0 || ns > 99999) {
            error("Ns doit être entre 0 et 99999");
            return;
        }
        server.inject(new FakeGenerator(txtNs.getText()));
        String message = server.sendBack();
        txtMessageEchange.setText(message);
        messageServerSended = false;
    }//GEN-LAST:event_btnStep2ActionPerformed

    private void btnStep5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep5ActionPerformed
        
        if (status == Status.ClientConnected && messageServerSended) {
            this.status = Status.Negociating;
        }
        if (!messageServerSended) {
            error("La réponse du serveur n'a pas été encore reçu.");
            return;
        }
        if (status != Status.Negociating) {
            error("Le client n'est pas prêt pour cette étape.");
            return;
        }
        client.setStatus(status);
        
        if (txtIV5.getText().isEmpty()) {
            txtIV5.setText(generator.genRandomIV());
        }
        if (txtIV5.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV5.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        client.inject(new FakeGenerator(txtIV5.getText()));
        String message = client.sendBack();
        txtMessageEchange.setText(message);
        messageClientSended = false;
    }//GEN-LAST:event_btnStep5ActionPerformed

    private void btnStep6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep6ActionPerformed
        
        if (status == Status.Negociating && messageClientSended) {
            this.status = Status.TrustEstablished;
        }
        if (!messageClientSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.TrustEstablished) {
            error("Le serveur n'est pas prêt pour cette étape.");
            return;
        }
        server.setStatus(status);
        
        if (txtNs1.getText().isEmpty()) {
            txtNs1.setText(generator.genRandomN());
        }
        int ns = getAsInt(txtNs1.getText());
        if (ns < 0 || ns > 99999) {
            error("Ns1 doit être entre 0 et 99999");
            return;
        }
        
        if (txtIV6.getText().isEmpty()) {
            txtIV6.setText(generator.genRandomIV());
        }
        if (txtIV6.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV6.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        server.inject(new FakeGenerator(txtNs1.getText(), txtNs1.getText(), txtIV6.getText()));
        String message = server.sendBack();
        txtMessageEchange.setText(message);
        messageServerSended = false;
    }//GEN-LAST:event_btnStep6ActionPerformed

    private void btnStep7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep7ActionPerformed
        
        if (status == Status.TrustEstablished && messageServerSended) {
            this.status = Status.AtemptingLogging;
        }
        if (!messageServerSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.AtemptingLogging) {
            error("Le client n'est pas prêt pour cette étape.");
            return;
        }
        client.setStatus(status);
        
        if (txtIV7.getText().isEmpty()) {
            txtIV7.setText(generator.genRandomIV());
        }
        if (txtIV7.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV7.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        if (txtId.getText().isEmpty() || txtPassword.getText().isEmpty()) {
            error("Vous devez entrer l'authentification à cette étape.");
            return;
        }
        client.inject(new FakeGenerator(txtIV7.getText()));
        client.setNumCompte(txtId.getText());
        client.setPassword(txtPassword.getText());
        String message = client.sendBack();
        txtMessageEchange.setText(message);
        messageClientSended = false;
    }//GEN-LAST:event_btnStep7ActionPerformed

    private void btnStep8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep8ActionPerformed
        
        if (status == Status.AtemptingLogging && messageClientSended) {
            this.status = Status.Authenticate;
        }
        if (!messageClientSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.Authenticate) {
            error("Le serveur n'est pas prêt pour cette étape.");
            return;
        }
        server.setStatus(status);
        
        if (txtNs2.getText().isEmpty()) {
            txtNs2.setText(generator.genRandomN());
        }
        int ns = getAsInt(txtNs2.getText());
        if (ns < 0 || ns > 99999) {
            error("Ns2 doit être entre 0 et 99999");
            return;
        }
        
        if (txtIV8.getText().isEmpty()) {
            txtIV8.setText(generator.genRandomIV());
        }
        if (txtIV8.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV8.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        server.inject(new FakeGenerator(txtNs2.getText(), txtNs2.getText(), txtIV8.getText()));
        String message = server.sendBack();
        txtMessageEchange.setText(message);
        messageServerSended = false;
    }//GEN-LAST:event_btnStep8ActionPerformed

    private void btnStep9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep9ActionPerformed
        
        if (((status == Status.ClientLogged && server.getStatus() != Status.WaitingForConnection) || 
                status == Status.Authenticate) && messageServerSended) {
            this.status = Status.Logged;
        }
        if (!messageServerSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.Logged) {
            error("Le client n'est pas prêt pour cette étape.");
            return;
        }
        client.setStatus(status);
        
        if (txtNc1.getText().isEmpty()) {
            txtNc1.setText(generator.genRandomN());
        }
        int nc1 = getAsInt(txtNc1.getText());
        if (nc1 < 0 || nc1 > 99999) {
            error("Nc1 doit être entre 0 et 99999");
            return;
        }
        
        if (txtIV9.getText().isEmpty()) {
            txtIV9.setText(generator.genRandomIV());
        }
        if (txtIV9.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV9.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        
        String operation = getSelected(btnGrpOperation);
        
        if ("TRANSFERT".equals(operation)) {
            if (txtDestination.getText().isEmpty()) {
                error("La destination doit saisie entré pour cette operation.");
                return;
            }
            if (txtMontant.getText().isEmpty()) {
                error("Le montant doit être saisie pour cette operation.");
                return;
            }
            if (!isMontantValid(txtMontant.getText())) {
                error("Le montant doit être au format AAA$ (trois chiffre et un signe '$').");
                return;
            }
        }
        
        client.inject(new FakeGenerator(txtNc1.getText(), txtNc1.getText(), txtIV9.getText()));
        client.setOperation(operation);
        client.setDestination(txtDestination.getText());
        client.setMontant(txtMontant.getText());
        String message = client.sendBack();
        txtMessageEchange.setText(message);
        messageClientSended = false;
    }//GEN-LAST:event_btnStep9ActionPerformed

    private void btnStep10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStep10ActionPerformed
        
        if (status == Status.Logged && messageClientSended) {
            this.status = Status.ClientLogged;
        }
        if (!messageClientSended) {
            error("La réponse du client n'a pas été encore reçu.");
            return;
        }
        if (status != Status.ClientLogged) {
            error("Le serveur n'est pas prêt pour cette étape.");
            return;
        }
        
        server.setStatus(status);
        
        if (txtIV10.getText().isEmpty()) {
            txtIV10.setText(generator.genRandomIV());
        }
        if (txtIV10.getText().length() != 6) {
            error("IV doit être de 6 caractères");
            return;
        }
        if (!Language.isValid(txtIV10.getText())) {
            error("IV doit être inclus dans le Langage L0");
            return;
        }
        server.inject(new FakeGenerator(txtIV10.getText()));
        String message = server.sendBack();
        txtMessageEchange.setText(message);
        messageServerSended = false;
    }//GEN-LAST:event_btnStep10ActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        String msg = "Aide\n";
        msg += "- Le boutton Recommencer permet de revenir à l'étape 1.\n";
        msg += "- Pour reprendre l'étape en cours, simplement cliquer sur son numéro.\n";
        msg += "- Pour des fins de test, l'application permet de ré-exécuter une étape \n"; 
        msg += "et renvoyer son message, tant que l'étape suivante n'est pas exécuté.";
        JOptionPane.showMessageDialog(this, msg, "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void error(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private int getAsInt(String value) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException ex) {
            return -1;
        }
    }
    
    private String getSelected(ButtonGroup btnGrp) {
        for (Enumeration<AbstractButton> buttons = btnGrp.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "";
    }
    
    private boolean isMontantValid(String value) {
        return value.length() == 4 && isNumeric(value.charAt(0)) && isNumeric(value.charAt(1)) && 
                isNumeric(value.charAt(2)) && value.charAt(3) == '$';
    }
    
    private boolean isNumeric(char c) {
        return c >= '0' && c <= '9';
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.ButtonGroup btnGrpOperation;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRecommencer;
    private javax.swing.JButton btnStep1;
    private javax.swing.JButton btnStep10;
    private javax.swing.JButton btnStep2;
    private javax.swing.JButton btnStep3;
    private javax.swing.JButton btnStep4;
    private javax.swing.JButton btnStep5;
    private javax.swing.JButton btnStep6;
    private javax.swing.JButton btnStep7;
    private javax.swing.JButton btnStep8;
    private javax.swing.JButton btnStep9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblClientMessage;
    private javax.swing.JLabel lblServerMessage;
    private javax.swing.JRadioButton radioQuitter;
    private javax.swing.JRadioButton radioTransfert;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtIV10;
    private javax.swing.JTextField txtIV4;
    private javax.swing.JTextField txtIV5;
    private javax.swing.JTextField txtIV6;
    private javax.swing.JTextField txtIV7;
    private javax.swing.JTextField txtIV8;
    private javax.swing.JTextField txtIV9;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtK0;
    private javax.swing.JTextField txtMessageEchange;
    private javax.swing.JTextField txtMontant;
    private javax.swing.JTextField txtNc;
    private javax.swing.JTextField txtNc1;
    private javax.swing.JTextField txtNs;
    private javax.swing.JTextField txtNs1;
    private javax.swing.JTextField txtNs2;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
